### ISSUE TITLE
Policy Remediation - Log Analytics Contributor role not enough ? missing 'Microsoft.OperationalInsights/workspaces/sharedKeys/action' 

### ISSUE THREAD

**Issue by cbezenco** [JimGBritt/AzurePolicy#17]
Not sure if the error I get is due to the fact that I did not follow exaclty the process described or because I am applying the iniatives to a RG and my LAW is in a different RG but I am getting the following error when applying the remediation task. 

Checking Monitor roles under https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#monitor it looks like in order to access the sharedKeys, we need "Monitoring Contributor" role but the Policy seems to be configured with Log Analytics Contributor in "roleDefinitionIds". 

Did I miss something ?

Detailed error.
{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "Forbidden",
      "message": "{\r\n  \"error\": {\r\n    \"code\": \"LinkedAuthorizationFailed\",\r\n    \"message\": \"The client '11fcfc2f-4467-4d38-b9b7-f8f1e808bfdd' with object id '11fcfc2f-4467-4d38-b9b7-f8f1e808bfdd' has permission to perform action 'Microsoft.Insights/diagnosticSettings/write' on scope '/subscriptions/91bb19d8-d81c-47fc-ad7d-0b67d426dc39/resourcegroups/IP-Law-Policy-Test/providers/Microsoft.Storage/storageAccounts/storepolicytest01/providers/Microsoft.Insights/diagnosticSettings/cbezinitiatives - LAW LabSecMonitoring'; however, it does not have permission to perform action 'Microsoft.OperationalInsights/workspaces/sharedKeys/action' on the linked scope(s) '/subscriptions/91bb19d8-d81c-47fc-ad7d-0b67d426dc39/resourcegroups/labsec/providers/microsoft.operationalinsights/workspaces/labsecmonitoring' or the linked scope(s) are invalid.\"\r\n  }\r\n}"
    }
  ]
}

**Comment by cbezenco** [comment]
It looks like I must have being doing something wrong when generating the original scripts or there might have been some delay as I got remediation working this morning (still not sure what I did wrong).

**Comment by cbezenco** [comment]
I should have read the documentation

https://docs.microsoft.com/en-us/azure/governance/policy/how-to/remediate-resources
If a resource modified by deployIfNotExists or modify is outside the scope of the policy assignment or the template accesses properties on resources outside the scope of the policy assignment, the assignment's managed identity must be manually granted access or the remediation deployment will fail.

**Comment by KamilWiecek** [comment]
@cbezenco you can use this script to fix msi role assignments on :
https://automate.guru/fix-msi-role-assignment/

**Comment by JimGBritt** [comment]
> If a resource modified by deployIfNotExists or modify is outside the scope of the policy assignment or the template accesses properties on resources outside the scope of the policy assignment, the assignment's managed identity must be manually granted access or the remediation deployment will fail.

@cbezenco 
I have been meaning to take a look and see if AssignPermissions would solve this.  I have it already leveraged for Event Hubs as a sink point.  Given the scope is an RG and the LA Workspace is in another RG, using AssignPermissions should give the MI rights during the assignment process.  Happy to take a PR on this if you can test and let me know.

https://docs.microsoft.com/en-us/azure/governance/policy/concepts/definition-structure#:~:text=assignPermissions%3A%20%28Optional%29%20Set%20as%20true%20to%20have%20Azure,in%20all%20of%20the%20policies%20in%20the%20initiative%29.  See below as an example.

```
$JSONPARMS = @'
{
            "profileName": {
                "type": "String",
                "metadata": {
                    "displayName": "Profile Name for Config",
                    "description": "The profile name Azure Diagnostics"
                }
            },
            "eventHubName": {
                "type": "String",
                "metadata": {
                    "displayName": "EventHub Name",
                    "description": "The event hub for Azure Diagnostics",
                    "strongType": "Microsoft.EventHub/Namespaces/EventHubs",
                    "assignPermissions": true
                }
            },
```
