### ISSUE TITLE
Policies generated via Create-AzDiagPolicy are showing Non-Compliant

### ISSUE THREAD

**Issue by CharbelNemnom** [JimGBritt/AzurePolicy#25]
Hello Jim,

I have looked at the policy script for creating/generating the diagnostic settings config to Event Hub. 
I have noticed that all Policies were showing Non-compliant, after some analysis, I found that the Current and Target values were not matching. The Current was empty.
I've changed the Template manually under deployIfNotExists/existenceCondition field: from eventHubName to eventHubAuthorizationRuleId, and then the policy gets compliant.

Thanks,
-Charbel

**Comment by JimGBritt** [comment]
@CharbelNemnom  first thank you for raising up the issue.  Sorry just seeing this now.

Can you please provide an example of what you are changing from / to in the exported policy within the comments section here?  

To be clear the EventHubRuleID depends on the EventHub in the policy.  You say you have to hardcode these, you should not have to as they are both supported by strongType.  Is it broken in the portal or via PowerShell and can you explain a bit more please?  Meanwhile, I will do some testing myself but I haven't changed the logic on that and it has been working for literally years but will take a look.

**Comment by CharbelNemnom** [comment]
Thank you @JimGBritt for your kind response,

Here is the deployIfNotExists section generated by default Create-AzDiagPolicy script:

**"effect": "deployIfNotExists",
            "details": {
              "type": "Microsoft.Insights/diagnosticSettings",
              "existenceCondition": {
                "allOf": [
                  {
                    "field": "Microsoft.Insights/diagnosticSettings/logs.enabled",
                    "equals": "[[parameters('logsEnabled')]"
                  },
                  {
                    "field": "Microsoft.Insights/diagnosticSettings/metrics.enabled",
                    "equals": "[[parameters('metricsEnabled')]"
                  },
                  {
                    "field": "Microsoft.Insights/diagnosticSettings/eventHubName",
                    "equals": "[[last(split(parameters('eventHubName'), '/'))]"
                  }
                ]
              },**

I have changed the last field **eventHubName** to **eventHubAuthorizationRuleId** and the parameter to **eventHubRuleId** as shown below in order to have the policy as compliant in the portal. The Current and Target values were not matching. The Current value was always empty.

  **"effect": "deployIfNotExists",
        "details": {
          "type": "Microsoft.Insights/diagnosticSettings",
          "existenceCondition": {
            "allOf": [
              {
                "field": "Microsoft.Insights/diagnosticSettings/logs.enabled",
                "equals": "[parameters('logsEnabled')]"
              },
              {
                "field": "Microsoft.Insights/diagnosticSettings/metrics.enabled",
                "equals": "[parameters('metricsEnabled')]"
              },
              {
                "field": "Microsoft.Insights/diagnosticSettings/eventHubAuthorizationRuleId",
                "equals": "[parameters('eventHubRuleId')]"
              }
            ]
          },**

Hope that helps!

Thanks,

**Comment by JimGBritt** [comment]
@CharbelNemnom thank you. An update from my side, it is working as I have it for me so I need to understand what your environment may have that is different related to the configuration of EH or EH RuleID.  Here is the process I have.

1. Initially Create the ARM template utilizing a subscription I selected from a list provided as reference

```
.\Create-AzDiagPolicy.ps1 -ExportDir C:\Users\jbritt\Documents\Github\demo\EHTest -ExportEH -ExportAll -ExportInitiative -AllRegions
```

2. Next I deploy it to my subscription

```
New-AzDeployment -Name DiagAzurePolicyInit -Location eastus -TemplateFile .\ARM-Template-azurepolicyinit.json
```

3. Then I assign to my subscription as a scope
![image](https://user-images.githubusercontent.com/13633751/101498880-7421ac80-3921-11eb-8a9f-554da01b8e6f.png)

4. Then I trigger a policy evaluation to have my assignment match reality according to policy

```
.\Trigger-PolicyEvaluation.ps1 -interval 5 -SubscriptionId yyyyyyyy-993b-41e8-9212-xxxxxxxxxxxx
``` 

5. Before I trigger any remediation, I validate my resource does not have EH profile configured for Azure Diagnostics

6. Then trigger (from portal / API shouldn't matter) to remediate (I have a script to do this which makes this way easier but I just grabbed a resource to remediate.

![image](https://user-images.githubusercontent.com/13633751/101500058-d0d19700-3922-11eb-9ecb-ed826a9ed4d0.png)

![image](https://user-images.githubusercontent.com/13633751/101500224-06768000-3923-11eb-962e-fe04fe071e0a.png)

7. Resource shows compliant

![image](https://user-images.githubusercontent.com/13633751/101500704-afbd7600-3923-11eb-89c8-d84befed900d.png)


What specifically isn't showing compliant.  Given you can only support Event Hub per region for resources in that region, are you seeing something related to compliance with that?  I'm trying to understand what you are solving with the parameter change in your example above.  Do you actually get diagnostics data flowing or does it just fix the compliance state to compliant?

Thank you for taking the time to lean in and support. If we have a bug, I want to fix it.  I just don't know what is going on just yet.

Thanks.
Jim

**Comment by JimGBritt** [comment]
Closing this one out as I cannot repro and there are some updates to the script that may resolve for the remediation piece on the initiative so please review and if needed, please re-open with current status.  Thanks!
