### ISSUE TITLE
Azure VM displays as compliant, but VM diagnostic settings blade still warns to enable diagnostics?

### ISSUE THREAD

**Issue by jeroenwo** [JimGBritt/AzurePolicy#27]
Thanks for your awesome script, it really helps us out!

While testing the various resources for monitoring, I found that the Azure VM policy shows up as compliant, but when visiting the VM Diagnostic settings blade it states that guest-level monitoring still needs to be enabled:
![image](https://user-images.githubusercontent.com/13014081/106630816-73ea0a00-657c-11eb-905c-d011a18ed1d4.png)

Also the Insights tab is not configured (as it requires a lot more parameters).

Is that something that still needs to be done manually/scripted, for example configuring the performance counters/event logs/sinks/agents of the VM? And the policy provided remediation is the basic diagnostics?

**Comment by JimGBritt** [comment]
@jeroenwo - thanks for the issue raised.  This policy is actually a no op for VMs.  The Diagnostics tab you are looking at for VMs is for something else (not Azure Diags / platform logs).  You should leverage the AMA / Log Analytics agent to capture both metrics and logs from VMs and you can enable that agent deployment via policy as well through the VM extension.  I can consider removing the VM Diagnostics policy but if configured, it actually doesn't capture anything. The challenge is there is a schema being exposed and that is why I am dynamically generating this policy.

**Comment by jeroenwo** [comment]
Thanks @JimGBritt. I already added the policies specific for VM monitoring with Log Analytics (see https://docs.microsoft.com/en-us/azure/azure-monitor/insights/vminsights-enable-policy). Thanks for the explanation!
