### ISSUE TITLE
Error with Static Websites

### ISSUE THREAD

**Issue by iisworks** [JimGBritt/AzurePolicy#38]
Ran the script, created an initiative that works for most resource types, but not for **microsoft.web/staticsites**:

"errorMessage": "The attempt to retrieve resources of type 'Microsoft.Insights/diagnosticSettings' for the 'DeployIfNotExists' policy resulted in a BadRequest response with error '{\"code\":\"ResourceTypeNotSupported\",\"message\":\"The resource type 'microsoft.web/staticsites' does not support diagnostic settings.\"}

From what I read the script should auto-detect all resource types that support diags. Is there an option planned to easily exclude certain resource types from being exported, e.g. a parameter ExcludeResourceTypes (for example to skip preview resources)? 

Thanks for the script BTW! We have been struggling with configuring diags in a robust and consistent manner, and the automation runbook we setup 3 years ago doesn't handle 1000 subscriptions and 50 resource types very well any more. I was hoping for years that diags settings would show up in Resource Graph at a certain point so we could run a query instead of having to check individual resources, but I guess that's not going to happen. :)

**Comment by JimGBritt** [comment]
@iisworks thanks for the feedback.  So the "dirty little secret" is that my script sniffs out RPs  that are in process of enabling diagnostics but haven't yet fully implemented.  So - ironically this is likely something in progress but not yet fully implemented. This is an unfortunate side effect of the script but also an early view into what is coming.  One option is to exclude these resourceTypes and leverage this script with a pipeline that I have published that will run on a schedule and then if a diff occurs in Git within DevOps, it can notify you that a change has occurred and you'll be able to see if this resourceType (or others) are now supported, etc.  Not sure that is helpful here but it is all I got for now :) - I can look at a way to exclude via the script but this would be the same as doing it in the portal to a certain extent and I wanted to ensure customers were aware what they were excluding.  Open to feedback here.  Here is the pipeline project I was mentioning: https://github.com/JimGBritt/AzureDiagnosticsPipeline which is actually a great way to test in pre-prod for any changes to the scripts as they occur (which one is coming soon).

**Comment by iisworks** [comment]
Thanks for the update, that makes sense. I'll check out the pipeline as well. As far as options go: I think it would be great if there was an "ExcludeResourceTypes" switch for the script to ignore RPs for any reason. I was creating a small PS wrapper script tailored to our needs to get all RPs from a representative MG and generate one initiative for it and assign it on a Test MG. Being able to exclude problematic and/or unneeded RPs from there would help a lot I think. It might even be worth considering an include file with an explicit list of RPs to be added to the exported initiative?

BTW: Do you happen to know if there are any generic Azure built-in policies planned that will provide this functionality out-of-the-box for any supported/selected resource type? And if Diagnostics settings will eventually be supported by Azure Resource Graph? :smile:

**Comment by JimGBritt** [comment]
@iisworks I'll look into your first question on exclusion - I don't disagree.

Related to providing an explicit list, etc. the real reason this script exists is to provide visibility into what is supported and not.  And to make it easier for customers to onboard using policy for Diags.  So adding things that may require upkeep and are not dynamically created is something that I have avoided in the past. If it fits for the majority, I usually implement it. I have also avoided any breaking changes that make the script drastically different so every time I update, I have to keep that in mind. 

Related to your thoughts on generic built ins, yes the future will be that.  Soon we'll have something that will allow for allLogs to be selected by default similar to metrics which technically is an "AllMetrics" option.  You may already see some of this in the UI.  Once we have this fully implemented, this will allow for a single built in policy to support all resourceTypes.  The challenge is building the list of RPs that support Logs in diags. Not all of them do. That is also why this script exists.  This is something that is being worked on as well to make this a better experience overall.

Great question on ARG and Diag settings.  I believe so. The challenge is this - Diagnostic settings are a proxy resourceType.  That means they are not tracked by ARM.  Technically they sit on top of a resource tracked by ARM so they are essentially a configuration not an ARM resource (a proxy).  This means it is difficult to implement in ARG as ARG is essentially building a cache of ARM changes (all which are tracked).  Today the only proxy resource Type that I am aware of that is tracked by ARG is VM State - I'm hopeful we'll see some other proxy resources showing up such as Diagnostics but I cannot comment on the future of that at this point.

**Comment by iisworks** [comment]
@JimGBritt Thanks again for the elaborate answers, much appreciated! Looking forward to the updates mentioned! :)

Sorry for the off-topic talk, I will close the issue for now.
